# Generated by Django 3.1.7 on 2021-03-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Student_profile', serialize=False, to='users.user')),
                ('study_class', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Teacher_profile', serialize=False, to='users.user')),
                ('subject', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
